platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: pal-tracker-1
  - name: version

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
    cd pal-tracker-1
    chmod +x gradlew
    ./gradlew -P version=$(cat ../version/number) build
    cp build/libs/pal-tracker-1-*.jar ../build-output
